play_motion:
  motions:
    hands_walk:
      joints: [arm_right_1_joint, arm_right_2_joint, arm_right_3_joint,
        arm_right_4_joint, arm_right_5_joint, arm_right_6_joint,
        arm_right_7_joint, arm_left_1_joint, arm_left_2_joint,
        arm_left_3_joint, arm_left_4_joint, arm_left_5_joint, arm_left_6_joint,
        arm_left_7_joint, torso_1_joint, torso_2_joint, head_1_joint,
        head_2_joint, hand_right_thumb_joint, hand_right_index_joint,
        hand_right_middle_joint, hand_left_thumb_joint, hand_left_index_joint,
        hand_left_middle_joint]
      points:
      - positions: [-0.44, 0.26, 0.0, 0.88, 0.0, 0.0, 0.0, -0.44, 0.26, 0.0,
        0.88, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.5, 3.5, 0.0, 3.5, 3.5]
        time_from_start: 0.0
    hands_front:
      joints: [arm_right_3_joint, arm_right_4_joint, arm_right_1_joint, arm_left_4_joint,
        arm_left_1_joint, arm_left_2_joint, arm_right_2_joint, arm_left_3_joint]
      points:
      - positions: [-1.0, 1.65, 1.2, 1.65, 1.2, 0.3, 0.3, -1.0]
        time_from_start: 0.0
    hands_up:
      joints: [torso_2_joint, arm_right_6_joint, arm_right_5_joint, arm_left_5_joint,
        torso_1_joint, arm_left_4_joint, head_2_joint, arm_right_2_joint, arm_left_3_joint,
        head_1_joint, arm_right_7_joint, arm_right_3_joint, arm_right_4_joint, arm_right_1_joint,
        arm_left_1_joint, arm_left_2_joint]
      points:
      - positions: [0.0, 0.0, -0.5, -0.5, 0.0, 1.3, 0.34, 0.0, -1.6, 0.0, 0.0, -1.6,
          1.4, 1.2, 0.9, 0.2]
        time_from_start: 0.0
    home:
      joints: [arm_left_7_joint, leg_left_1_joint, arm_right_6_joint, torso_2_joint,
        arm_right_5_joint, arm_left_5_joint, arm_left_6_joint, arm_left_1_joint, torso_1_joint,
        arm_left_4_joint, head_2_joint, leg_right_3_joint, leg_left_2_joint, arm_right_2_joint,
        leg_left_6_joint, head_1_joint, leg_right_6_joint, arm_right_7_joint, arm_right_3_joint,
        leg_left_5_joint, leg_right_4_joint, arm_right_4_joint, arm_left_3_joint,
        leg_right_1_joint, leg_left_4_joint, leg_right_5_joint, arm_left_2_joint,
        arm_right_1_joint, leg_right_2_joint, leg_left_3_joint]
      points:
      - positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
          0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
          0.0, 0.0]
        time_from_start: 0.0
    small_squat:
      joints: [leg_left_4_joint, leg_right_3_joint, leg_right_5_joint, leg_left_5_joint,
        leg_right_4_joint, leg_left_3_joint]
      points:
      - positions: [1.0, -0.5, -0.5, -0.5, 1.0, -0.5]
        time_from_start: 0.0
    squat:
      joints: [arm_left_7_joint, leg_left_1_joint, arm_right_6_joint, torso_2_joint,
        arm_right_5_joint, arm_left_5_joint, arm_left_6_joint, arm_left_1_joint, torso_1_joint,
        arm_left_4_joint, head_2_joint, leg_right_3_joint, leg_left_2_joint, arm_right_2_joint,
        leg_left_6_joint, head_1_joint, leg_right_6_joint, arm_right_7_joint, arm_right_3_joint,
        leg_left_5_joint, leg_right_4_joint, arm_right_4_joint, arm_left_3_joint,
        leg_right_1_joint, leg_left_4_joint, leg_right_5_joint, arm_left_2_joint,
        arm_right_1_joint, leg_right_2_joint, leg_left_3_joint]
      points:
      - positions: [0.0, 0.0, 0.0, -0.15, 0.0, 0.0, 0.0, 0.0, 0.0, 0.9, 0.25, -1.35,
          0.0, 1.3, 0.0, 0.0, 0.0, 0.0, 0.0, -1.3, 2.6, 0.9, 0.0, 0.0, 2.6, -1.3,
          1.3, 0.0, 0.0, -1.35]
        time_from_start: 0.0

    # inherited from reemh3
    # *********************

    arms_t:
      joints: [torso_1_joint, torso_2_joint, head_1_joint, head_2_joint, arm_left_1_joint,
        arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint, arm_left_6_joint,
        arm_left_7_joint, arm_right_1_joint, arm_right_2_joint, arm_right_3_joint,
        arm_right_4_joint, arm_right_5_joint, arm_right_6_joint, arm_right_7_joint]
      points:
      - positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.707, 0.0, 0.1, 0.0, 0.0, 0.0, 0.0,
          0.707, 0.0, 0.1, 0.0, 0.0, 0.0]
        time_from_start: 0.0
      meta:
        name: Arms T
        usage: posture
        description: Both arms set straight pointing sideways at 45 degrees.

    # see #7528
    bow:
      joints: [arm_left_7_joint, arm_right_7_joint, torso_2_joint, arm_right_6_joint,
        arm_right_3_joint, arm_left_6_joint, arm_left_5_joint, arm_right_4_joint,
        arm_right_1_joint, torso_1_joint, arm_left_4_joint, arm_left_1_joint, arm_left_2_joint,
        arm_right_2_joint, arm_right_5_joint, arm_left_3_joint, head_2_joint, head_1_joint]
      points:
      - positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.88, -0.44, 0.0, 0.88, -0.44,
          0.26, 0.26, 0.0, 0.0, 0.0, 0.0]
        time_from_start: 0.0
      - positions: [0.0, 0.0, 0.4, 0.0, -0.05, 0.0, 0.0, 0.6109, -0.1, 0.0, 0.6109,
          -0.1, 0.1, 0.1, 0.0, -0.05, 0.3, 0.0]
        time_from_start: 2.0
      - positions: [0.0, 0.0, 0.4, 0.0, -0.05, 0.0, 0.0, 0.6109, -0.1, 0.0, 0.6109,
          -0.1, 0.1, 0.1, 0.0, -0.05, 0.3, 0.0]
        time_from_start: 2.3
      - positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.88, -0.44, 0.0, 0.88, -0.44,
          0.26, 0.26, 0.0, 0.0, 0.0, 0.0]
        time_from_start: 4.5
    open_arms:
      joints: [arm_right_5_joint, hand_left_index_joint, arm_left_4_joint, arm_right_2_joint,
        arm_left_3_joint, hand_right_index_joint, arm_right_3_joint, hand_right_middle_joint,
        arm_right_4_joint, arm_left_2_joint, hand_left_middle_joint, arm_left_7_joint,
        arm_right_6_joint, arm_left_5_joint, arm_left_6_joint, head_2_joint, torso_2_joint,
        arm_right_1_joint, head_1_joint, arm_right_7_joint, torso_1_joint, arm_left_1_joint]
      points:
      - positions: [0.0, 3.5, 0.88, 0.26, 0.0, 3.5, 0.0, 3.5, 0.88, 0.26, 3.5, 0.0,
          0.0, 0.0, 0.0, 0.0, 0.0, -0.44, 0.0, 0.0, 0.0, -0.44]
        time_from_start: 0.0
      - positions: [0.0, 0.0, 1.8, 0.2, -0.2, 0.0, -0.2, 0.0, 1.8, 0.2, 0.0, 0.0,
          0.3, 0.0, 0.3, 0.1, -0.1, 0.3, 0.0, 0.0, 0.0, 0.3]
        time_from_start: 1.4
      - positions: [0.0, 0.0, 1.6, 0.3, 0.0, 0.0, 0.0, 0.0, 1.6, 0.3, 0.0, 0.0, 0.3,
          0.0, 0.3, 0.15, -0.15, 0.6, 0.0, 0.0, 0.0, 0.6]
        time_from_start: 2.3
      - positions: [0.0, 0.0, 1.4, 0.2, 0.3, 0.0, 0.3, 0.0, 1.4, 0.2, 0.0, 0.0, 0.3,
          0.0, 0.3, 0.1, -0.1, 0.4, 0.0, 0.0, 0.0, 0.4]
        time_from_start: 2.9
      - positions: [0.0, 3.5, 0.88, 0.26, 0.0, 3.5, 0.0, 3.5, 0.88, 0.26, 3.5, 0.0,
          0.0, 0.0, 0.0, 0.0, 0.0, -0.44, 0.0, 0.0, 0.0, -0.44]
        time_from_start: 4.5
    point_front_left:
      joints: [hand_left_middle_joint, arm_left_7_joint, torso_2_joint, arm_left_5_joint,
        arm_left_6_joint, torso_1_joint, hand_left_index_joint, arm_left_4_joint,
        arm_left_1_joint, arm_left_2_joint, arm_left_3_joint, head_2_joint, head_1_joint]
      points:
      - positions: [3.5, 0.0, 0.0, 0.0, 0.0, 0.0, 3.5, 0.88, -0.44, 0.26, 0.0, 0.0,
          0.0]
        time_from_start: 0.0
      - positions: [0.0, 0.4, 0.0, 0.6, 0.2, 0.0, 0.0, 0.8, 1.0, 0.17, -0.9, 0.0,
          0.0]
        time_from_start: 1.5
      - positions: [0.0, 0.4, 0.0, 0.6, 0.2, 0.0, 0.0, 0.8, 1.0, 0.17, -0.9, 0.0,
          0.0]
        time_from_start: 2.5
      - positions: [3.5, 0.0, 0.0, 0.0, 0.0, 0.0, 3.5, 0.88, -0.44, 0.26, 0.0, 0.0,
          0.0]
        time_from_start: 4.0
    point_front_right:
      joints: [arm_right_7_joint, torso_2_joint, arm_right_6_joint, arm_right_3_joint,
        hand_right_middle_joint, arm_right_4_joint, head_2_joint, arm_right_1_joint,
        torso_1_joint, arm_right_2_joint, arm_right_5_joint, hand_right_index_joint,
        head_1_joint]
      points:
      - positions: [0.0, 0.0, 0.0, 0.0, 3.5, 0.88, 0.0, -0.44, 0.0, 0.26, 0.0, 3.5,
          0.0]
        time_from_start: 0.0
      - positions: [0.4, 0.0, 0.2, -0.9, 0.0, 0.8, 0.0, 1.0, 0.0, 0.17, 0.6, 0.0,
          0.0]
        time_from_start: 1.5
      - positions: [0.4, 0.0, 0.2, -0.9, 0.0, 0.8, 0.0, 1.0, 0.0, 0.17, 0.6, 0.0,
          0.0]
        time_from_start: 2.5
      - positions: [0.0, 0.0, 0.0, 0.0, 3.5, 0.88, 0.0, -0.44, 0.0, 0.26, 0.0, 3.5,
          0.0]
        time_from_start: 4.0
    shake_hand:
      joints: [arm_left_7_joint, arm_right_7_joint, hand_right_thumb_joint, arm_right_6_joint,
        arm_right_3_joint, arm_left_6_joint, hand_right_middle_joint, arm_left_5_joint,
        arm_right_4_joint, arm_left_3_joint, torso_1_joint, torso_2_joint, arm_left_1_joint,
        arm_left_2_joint, arm_right_2_joint, arm_left_4_joint, arm_right_5_joint,
        arm_right_1_joint, hand_right_index_joint]
      points:
      - positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.5, 0.0, 0.88, 0.0, 0.0, 0.0, -0.44,
          0.26, 0.26, 0.88, 0.0, -0.44, 3.5]
        time_from_start: 0.0
      - positions: [0.0, 0.0, 0.0, -0.2, -0.45, 0.0, 0.0, 0.0, 0.95, -0.175, 0.2,
          -0.1, -0.175, 0.17, 0.15, 0.6, 0.1, 0.35, 0.0]
        time_from_start: 1.25
      - positions: [0.0, 0.0, 0.0, -0.2, -0.45, 0.0, 0.0, 0.0, 0.95, -0.175, 0.2,
          -0.1, -0.175, 0.17, 0.15, 0.6, 0.1, 0.35, 0.0]
        time_from_start: 2.5
      - positions: [0.0, 0.0, 0.0, -0.2, -0.5, 0.0, 0.0, 0.0, 0.7, -0.175, 0.2, -0.09,
          -0.175, 0.17, 0.15, 0.6, 0.1, 0.4, 0.0]
        time_from_start: 3.25
      - positions: [0.0, 0.0, 0.0, -0.2, -0.45, 0.0, 0.0, 0.0, 0.95, -0.175, 0.2,
          -0.1, -0.175, 0.17, 0.15, 0.6, 0.1, 0.35, 0.0]
        time_from_start: 4.0
      - positions: [0.0, 0.0, 0.0, -0.2, -0.5, 0.0, 0.0, 0.0, 0.7, -0.175, 0.2, -0.09,
          -0.175, 0.17, 0.15, 0.6, 0.1, 0.4, 0.0]
        time_from_start: 4.75
      - positions: [0.0, 0.0, 0.0, -0.2, -0.45, 0.0, 0.0, 0.0, 0.95, -0.175, 0.2,
          -0.1, -0.175, 0.17, 0.15, 0.6, 0.1, 0.35, 0.0]
        time_from_start: 5.5
      - positions: [0.0, 0.0, 0.0, -0.2, -0.45, 0.0, 0.0, 0.0, 0.95, -0.175, 0.2,
          -0.1, -0.175, 0.17, 0.15, 0.6, 0.1, 0.35, 0.0]
        time_from_start: 6.75
      - positions: [0.0, 0.0, 0.0, -0.1, -0.2, 0.0, 3.5, 0.0, 1.2, -0.175, 0.1, -0.1,
          -0.175, 0.17, 0.22, 0.6, 0.1, 0.0, 3.5]
        time_from_start: 7.75
      - positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.5, 0.0, 0.88, 0.0, 0.0, 0.0, -0.44,
          0.26, 0.26, 0.88, 0.0, -0.44, 3.5]
        time_from_start: 9.25
    wave:
      joints: [arm_left_7_joint, arm_right_7_joint, torso_2_joint, arm_right_6_joint,
        arm_right_3_joint, arm_left_6_joint, hand_right_middle_joint, arm_left_5_joint,
        arm_right_4_joint, arm_left_2_joint, torso_1_joint, hand_right_index_joint,
        arm_left_4_joint, arm_left_1_joint, head_2_joint, arm_right_2_joint, arm_right_5_joint,
        arm_left_3_joint, arm_right_1_joint, head_1_joint]
      points:
      - positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.5, 0.0, 0.88, 0.26, 0.0, 3.5,
          0.88, -0.44, 0.0, 0.26, 0.0, 0.0, -0.44, 0.0]
        time_from_start: 0.0
      - positions: [0.0, 0.0, 0.0, 0.6, 0.4, 0.0, 0.0, 0.0, 2.0, 0.15, 0.0, 0.0, 0.3,
          0.1, 0.0, 0.15, -1.4, 0.0, 0.4, 0.0]
        time_from_start: 1.5
      - positions: [0.0, 0.0, 0.0, 0.6, -0.4, 0.0, 0.0, 0.0, 2.0, 0.15, 0.0, 0.0,
          0.3, 0.1, 0.25, 0.4, -1.4, 0.0, 0.4, 0.0]
        time_from_start: 2.3
      - positions: [0.0, 0.0, 0.0, 0.6, 0.4, 0.0, 0.0, 0.0, 2.0, 0.15, 0.0, 0.0, 0.3,
          0.1, 0.0, 0.15, -1.4, 0.0, 0.4, 0.0]
        time_from_start: 3.3
      - positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 3.5, 0.0, 0.88, 0.26, 0.0, 3.5,
          0.88, -0.44, 0.0, 0.26, 0.0, 0.0, -0.44, 0.0]
        time_from_start: 4.5
    were_here:
      joints: [arm_left_7_joint, arm_right_7_joint, torso_2_joint, arm_right_6_joint,
        arm_right_3_joint, arm_left_6_joint, arm_left_5_joint, arm_right_4_joint,
        arm_right_1_joint, torso_1_joint, arm_left_4_joint, arm_left_1_joint, arm_left_2_joint,
        arm_right_2_joint, arm_right_5_joint, arm_left_3_joint, head_2_joint, head_1_joint]
      points:
      - positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.88, -0.44, 0.0, 0.88, -0.44,
          0.26, 0.26, 0.0, 0.0, 0.0, 0.0]
        time_from_start: 0.0
      - positions: [0.7, 0.7, 0.1, 0.2, 0.18, 0.2, 0.7, 1.05, 0.0, 0.0, 1.05, 0.0,
          0.15, 0.15, 0.7, 0.18, 0.3, 0.0]
        time_from_start: 1.75
      - positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.88, -0.44, 0.0, 0.88, -0.44,
          0.26, 0.26, 0.0, 0.0, 0.0, 0.0]
        time_from_start: 3.5
